# Generated by Django 5.1.3 on 2025-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.CharField(default='Non specific', max_length=100),
        ),
    ]
