# Generated by Django 5.1.3 on 2025-07-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='animation',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
