# Generated by Django 5.1.3 on 2025-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_animation_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='animation',
        ),
        migrations.AddField(
            model_name='project',
            name='animation_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
