# Generated by Django 5.1.3 on 2025-11-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='animation_url',
            new_name='animation_url_1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='project',
            name='animation_url_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
