# Generated by Django 5.1.3 on 2025-11-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_animation_url_project_animation_url_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='animation_url_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
