# Generated by Django 5.1.3 on 2025-11-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_project_animation_url_2_alter_project_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_2',
        ),
    ]
