# Generated by Django 5.1.3 on 2025-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_project_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='animation_url_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='animation_url_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
