# Generated by Django 5.1.3 on 2025-11-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_animation_url_3_project_animation_url_4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='project',
            name='description_2',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='description_3',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='description_4',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
