# Generated by Django 5.1.3 on 2025-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_description_project_description_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='layout_type',
            field=models.IntegerField(default=1),
        ),
    ]
