# Generated by Django 5.1.3 on 2025-12-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project_layout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_10',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='description_5',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='description_6',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='description_7',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='description_8',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='project',
            name='description_9',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
