# Generated by Django 5.1.3 on 2026-04-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_project_description_10_project_description_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc_image_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='desc_image_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='desc_image_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='desc_image_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
